### PR TITLE
remove win7 and win8 msu

### PR DESCRIPTION
**Pull request by Wulian233**
https://github.com/python/cpython/pull/124672
Require at least Windows 10 for install (Python 3.13+)

This PR is part of the https://github.com/python/cpython/pull/124822
> Removed outdated Windows Updates. Since we stopped supporting Windows 7 and 8.1, these patches are no longer needed. The minimum version is now Windows 10.

Synced the latest vcruntime 14.42 (today): https://github.com/python/cpython-bin-deps/tree/vcruntime

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Thanks for PR, but note you'll probably need to wait for a core dev (zooba?) to make an equivalent change, since we need to be careful about accepting binaries.

There's supposed to be a PR closing workflow on this repo, but it looks like it might only run on cron

**Comment by Wulian233** [comment]
Thank you for reminding me! I didn't notice it before https://github.com/python/cpython-bin-deps/blob/main/.github%2Fworkflows%2Fautoclose.yaml
@zooba Could you review this, Thank you

**Comment by hugovk** [comment]
> There's supposed to be a PR closing workflow on this repo, but it looks like it might only run on cron

Yes, but https://github.com/python/cpython-bin-deps/actions/workflows/autoclose.yaml says:

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

I've re-enabled it.

We could have it run on PR open as well?

**Comment by Wulian233** [comment]
😥

**Comment by hugovk** [comment]
> We could have it run on PR open as well?

Please se PR https://github.com/python/cpython-bin-deps/pull/6.

**Comment by zooba** [comment]
> I've re-enabled it.

Hahaha, after all the trouble I went to to set it up 😆 

Virtually none of the branches in this repo are used directly, it's always through tags, so once files are added they can't really be removed. We already aren't using these files in any current builds, but there's nothing gained by deleting them.

**Pull request closed without merging**
